language: python

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql - "CREATE ROLE postgres WITH SUPERUSER LOGIN 'annet';" -U postgres
  - psql - "CREATE DATABASE test_one;" -U postgres

script:
  - nosetests --with-coverage

after_success:
  - coveralls